setwd("C:/GIT/strpackage/externalTests")
dat <- read.csv("sample.csv")
library(forecast)
my.ts <- msts(as.vector(dat$x), seasonal.periods = c(1440, 1440 * 7))
length(my.ts)

plot(my.ts)
library(stR)
#str1 = AutoSTR(my.ts, gapCV = 48, confidence = 0.95, robust = TRUE)
str1 = AutoSTR(my.ts, gapCV = 48, confidence = NULL, robust = FALSE)
plot(str1)
